### PR TITLE
WIP: Fix documentation

### PR DESCRIPTION
**Pull request by josenavas**
Porting some of the comments from Gail in the closed PR:
- [x] `16S-rrna-amplification-protocol.md`
  - line 3: The are some that are MiSeq
  - line 4: Some have ITS/18S
  - line 37: Primers:

```
Linker - CA
Primer - TGATCCTTCTGCAGGTTCACCTA - barcoded
Linker - GT
Primer - GTACACACCGCCCGTC
FWD:GTACACACCGCCCGTC; REV:TGATCCTTCTGCAGGTTCACCTAC
and ITS:
ITS1/2: 
Linker (rev) AT 
Primer (reverse) GCTGCGTTCTTCATCGATGC
Linker CG
Primer (forward) CTTGGTCATTTAGAGGAAGTAA - barcoded
```
- [x] emp-informatics-working-group.md
  - line 8: Change Rob's affiliation to UCSD
  - line 15: Add Gail's to UCSD
  - line 25: Is Folker still associated?
- [x] emp-laboratories.md
  - line 10: Change to : Rob Knight, Department of Pediatrics&Computer Science and Engineering, UCSD
  - line 16: Janet is at PNNL, new email is: (ask Gail)
- [ ] global-environmental-sample-database.md
  - line 54: Add sample info guide
- [x] members.md
  - Need to check all of these

### CODE REVIEW

**Comment by colinbrislawn** [comment]
>The idea would be to **do a PR per file**, so each of the PR is knocking down one of the items that can be checked in that list. Once all of them is merged, we can merge the big PR.

:

**Comment by ackermag** [comment]
Folker is no longer associated.

On Sat, Mar 12, 2016 at 11:16 AM, Colin Brislawn <notifications@github.com>
wrote:

> The idea would be to *do a PR per file*, so each of the PR is knocking
> down one of the items that can be checked in that list. Once all of them is
> merged, we can merge the big PR.
>
> :
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/emp/pull/54#issuecomment-195793496>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by cuttlefishh** [comment]
Re the primers in 16S-rrna-amplification-protocol.md -- #50 -- we need to make sure the sequencing primers are updated. I'm waiting on the branch/PR policy to be sorted out.

**Comment by ackermag** [comment]
Janet Jansson  Pacific Northwest National Laboratory janet.jansson@pnnl.gov

Primers:
2015:
ITS1/2: 
Linker (rev) AT 
Primer (reverse) GCTGCGTTCTTCATCGATGC
Linker (fwd) CG
Primer (forward) CTTGGTCATTTAGAGGAAGTAA - barcoded


2015: 16S rRNA
Linker (rev) CC
Primer (reverse) GGACTACNVGGGTWTCTAAT - barcoded
Linker (fwd) GT
Primer (forward) GTGYCAGCMGCCGCGGTAA

**Comment by colinbrislawn** [comment]
What is the citation for the new primers? Is there a paper out yet, or perhaps a preprint?

**Comment by ackermag** [comment]
There is a paper out:
*Citation* Walters W, Hyde ER, Berg-Lyons D, Ackermann G, Humphrey G,
Parada A, Gilbert JA, Jansson JK, Caporaso JG, Fuhrman JA, Apprill A,
Knight B. 2015. Improved bacterial 16S rRNA gene (V4 and V4-5) and fungal
internal transcribed spacer marker gene primers for microbial community
surveys. mSystems 1(1):e00009-15. doi:10.1128/mSystems.00009-15
<http://dx.doi.org/10.1128/mSystems.00009-15>.

On Tue, Mar 22, 2016 at 1:25 PM, Colin Brislawn <notifications@github.com>
wrote:

> What is the citation for the new primers? Is there a paper out yet, or
> perhaps a preprint?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/emp/pull/54#issuecomment-200005453>
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by cuttlefishh** [comment]
Is this the "V4-V5 primer set from Parada et al. (2015)" mentioned by Adam Rivers?

**Comment by colinbrislawn** [comment]
So it looks like the primers were first used / developed on Parada et al. (2015).
https://www.ncbi.nlm.nih.gov/pubmed/26271760

Walters et al (2016) is the paper evaluating the primers themselves. This includes more info and also the whole Knight lab. We probably want to cite this one. 
http://msystems.asm.org/content/1/1/e00009-15

**Comment by cuttlefishh** [comment]
Awesome. Thanks for the clarification.

**Pull request merged**
