### PR TITLE
Updating URLs

### PR DESCRIPTION
**Pull request by josenavas**
Updating the `data-urls.txt` file to include the new files.

### CODE REVIEW

**Comment by antgonza** [comment]
I think it will be nice to have files per folder per release and have one that is latests. This should be helpful for future releases. What do you think?

**Comment by josenavas** [comment]
Sounds reasonable. By release we use the date? E.g. this release will be January2015?

**Comment by antgonza** [comment]
Yes but let's do it like 1501 so it's easily sortable.

**Comment by gregcaporaso** [comment]
How about ``15-01``, so it's a little more human readable.

**Comment by antgonza** [comment]
You humans ... fine.

**Comment by josenavas** [comment]
Updated! The ftp site now has releases, in human readable form.

**Comment by gregcaporaso** [comment]
There are two mapping files in the ``data`` directory. I think those belong to an older version of the EMP results. Should we delete those as part of this PR, and just have users download all files (i.e., by providing the links in the txt file as you're doing now) ? I think that makes the most sense.

**Comment by gregcaporaso** [comment]
Note that that change would also require an update to ``README.md``.

**Comment by josenavas** [comment]
Thanks @gregcaporaso 
I've updated the readme and added all files to the ftp site. I've also updated the file names to follow the previous conventions.

**Pull request merged**
