### PR TITLE
compute alpha diversity using scikit bio

### PR DESCRIPTION
**Pull request by ekopylova**

### CODE REVIEW

**Comment by ekopylova** [comment]
@wasade could you take a look over this? Thanks!

**Comment by mortonjt** [comment]
Just an observation - this module looks very similar to alpha diversity in [qiime2](https://github.com/qiime2/q2-diversity/tree/master/q2_diversity/_alpha)

Do you think these kinds of scripts are still necessary?

**Comment by cuttlefishh** [comment]
This is for the EMP paper specifically. The goal is for the code we ran for the paper to be in the public repo, which it is. I don't think it's worth Jenya's time to make her code use the latest libraries.

**Comment by mortonjt** [comment]
Hi @cuttlefishh .  Don't get me wrong, I didn't meet to be critical.  But this would end up saving time, since many of these analyses can be run out of the box with qiime2 - so less code to upload and document.

But I don't have any strong preferences with this.

**Comment by ekopylova** [comment]
Nice @mortonjt ! I didn't know Qiime2 had this. Is most EMP analysis carried out with QIIME 1 or 2? This was a quick solution @wasade and I put together to avoid the >700Gb RAM required by QIIME 1.

**Comment by cuttlefishh** [comment]
Most of EMP is being done with QIIME 1 as far as I know. But it's fine if some notebooks use QIIME 2. Thanks @mortonjt for pointing that out and for reviewing the PR! I'm fine with whichever approach you guys decide to take with this notebook.

**Comment by ekopylova** [comment]
Well, running via Qiime2 would avoid me writing tests for this, so let's go that route ;)

**Comment by ekopylova** [comment]
Ok, alpha diversity has been computed and I think we can move forward with these results since they are based on a very simple wrapper around skbio.

**Comment by mortonjt** [comment]
+1

**Comment by cuttlefishh** [comment]
Excellent. Thanks Jenya!

**Comment by cuttlefishh** [comment]
I created a directory ipynb/analysis/05-alpha-diversity. Should we move Jenya's script there or just reference it where it is?

**Comment by cuttlefishh** [comment]
@ekopylova Can you close this PR and issue a new PR to emp/ipynb/analysis/05-alpha-diversity ?

**Pull request merged**
